spring.application.name=delivery-service-reactive
server.port=8082
springdoc.swagger-ui.path=/swagger-ui/index.html


logging.pattern.console = ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

spring.r2dbc.url=r2dbc:mysql://localhost:3306/order_schema?serverTimezone=Asia/Kolkata
spring.r2dbc.username=root
spring.r2dbc.password=shamit2020


rabbitmq.host=192.168.0.143
rabbitmq.port=5672
rabbitmq.username=admin
rabbitmq.password=admin
app.mq.source-queue=delivery-service-queue
app.mq.target-exchange=domain.events
app.mq.routing-key=delivery.created