spring.application.name=payment-service
server.port=8081
springdoc.swagger-ui.path=/swagger-ui/index.html

logging.pattern.console = ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

# MySQL R2DBC
spring.r2dbc.url=r2dbc:mysql://localhost:3306/order_schema?serverTimezone=Asia/Kolkata
spring.r2dbc.username=root
spring.r2dbc.password=shamit2020

# RabbitMQ (non-reactive)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin

# Rabbit config
app.rabbit.exchange=domain.events
app.rabbit.paymentExchange=payment.exchange
app.rabbit.paymentQueue=payment-service-queue

# Shared Symmetric AES Encryption Key (16 bytes = 128-bit key)
#openssl rand -base64 16
app.security.crypto-key=qu4YTpM2K16xEap2KDbFtQ==


